### ISSUE TITLE
Manifest exe overwritten when reproduce is true

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#265]
It should be possible to set
```yaml
manifest:
 reproduce:
   exe: True
```
and if the `manifest/exe.yaml` is correct, `payu` should not look for an executable in the `laboratory`.

Currently it works for one run, but if the executable doesn't exist the manifest is overwritten. If there is a valid exe path it doesn't, unsurprisingly.
