### ISSUE TITLE
Get model executables from path 

### ISSUE THREAD

**Issue by micaeljtoliveira** [payu-org/payu#379]
Recently we added the option to install ACCESS-OM3 with Spack.  Usually the location where Spack installs the packages includes a hash in the naming scheme, which makes it a bit tedious to keep the full executable path up to date in the payu `config.yaml` file.  On the other hand, we are using Spack to automatically create environment modules for OM3 that add the corresponding path to the OM3 binaries to the PATH environment variable. Therefore it would be nice if payu could get the executable from the path.

Basically, instead of doing:

```yaml
exe: /g/data/ik11/spack/0.20.1/opt/linux-rocky8-cascadelake/intel-2021.6.0/access-om3-main-7cryrsy/bin/access-om3-MOM6-CICE6

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.3.0/linux-rocky8-cascadelake
  load:
      - access-om3
```

we would like to simply write:

```yaml
exe: access-om3-MOM6-CICE6

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.3.0/linux-rocky8-cascadelake
  load:
      - access-om3
```

**Comment by aidanheerdegen** [comment]
I like this idea as it makes easier for users to switch model versions, as there is no need to determine the (rather convoluted) paths to `spack` built executables.

Just out of interest, what is the reason to encode the configuration version in the `module use` path rather than the module itself?

e.g.
```yaml
exe: access-om3-MOM6-CICE6

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/linux-rocky8-cascadelake
  load:
      - access-om3/0.3.0
```

**Comment by micaeljtoliveira** [comment]
> Just out of interest, what is the reason to encode the configuration version in the module use path rather than the usual convention of defining in the call to module load?

This is because of how our Spack instance is currently set up. We are installing each version of OM3 in a different Spack environment (there's a couple of reasons for this, but this might stop doing it in the future). Then, because some versions have the same dependencies and because I didn't want to have the Spack hash in the module name, each environment needs a unique module path to install its modules. The simplest way to achieve that was to add the OM3 version to the module path. That explains why the version appears in the `use` statement. Regarding the `load` statement, one could actually specify the version, but since there's only one version of OM3 in that set of modules, there's no need.

**Comment by micaeljtoliveira** [comment]
I discussed this with @harshula yesterday and he raised a few valid concerns about picking stuff from `$PATH`. I therefore suggested the following alternative:

```
exe: $SPACK_ACCESS_OM3_ROOT/bin/access-om3-MOM6-CICE6

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.3.0/linux-rocky8-cascadelake
  load:
      - access-om3
```
This would work for the COSIMA spack instance, because each module defines an environment variable `SPACK_{name}_ROOT` that contains the installation prefix of the package. A similar solution could be adopted by ACCESS-NRI.

Currently the above proposal does not work because payu loads the modules **after** handling the executable, so the variable is not defined when needed. Might not be too hard to change this.

**Comment by harshula** [comment]
Is it possible to require a module version? e.g. `access-om3/x.y.z`. Not requiring a version can cause unexpected problems for users that we'll have to debug.

**Comment by micaeljtoliveira** [comment]
Just be aware that if you check that there's a version, that the version naming scheme might be a lot more complicated than 'x.y.z'. You also cannot assume that the module will always have the form `{name}/{version}`, as one could have written the above example as:
```
modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.3.0/
  load:
      - linux-rocky8-cascadelake/access-om3/0.3.0
   
```
