### ISSUE TITLE
Specifying executables to reproduce fails to create links

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#388]
If I set
```yaml
manifest:
  reproduce:
    exe: True
```
the symlinks for the executables are not created. If I remove that option, or use the command line `-r` option, the symlinks are created correctly. Also works if I set all to `True`
```yaml
manifest:
  reproduce:
    exe: True
    input: True
    restart: True
```
This is with the the [`1deg_jra55_ryf`](https://github.com/ACCESS-NRI/access-om2-configs/tree/1deg_jra55_ryf) ACCESS-OM2 model configuration.

```
$ payu --version
payu 1.0.19
```
