### ISSUE TITLE
Log collate operations

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#438]
It would be good to have some machine-readable log of collate operations so there is a track of how files that were output from the model have been transformed. 

For example restart files that are collated break the link between the `restart.yaml` manifest and the restarts that were used in the model run. If that link could be re-established then collated restarts could be reliably used in place of the original tiled restarts.

For a collate log to be used in this manner it would have to include `md5` hashes for the collated and uncollated files and a relationship between them.

How to store this information in the commit history of the experiment repo is a problem that is shared with https://github.com/payu-org/payu/issues/437

**Comment by Qian-HuiChen** [comment]
Thanks @aidanheerdegen for raising this idea!

I drafted an example of collate mapping log file. It will be great if @aidanheerdegen  and @jo-basevi  could provide some feedback on this. Currently it is in json format.
```json
{
     "collate_ignored_files": {
            "ocean_ignore.res.nc.0000": "md5hash2"
        },
     "ocean_thickness.res.nc": {
            "path": "xxx/archive/yyy/output001/ocean/ocean_thickness.res.nc",
            "md5": "md5final",
            "collated_tiles": {
                "ocean_thickness.res.nc.0000": "md5hash0",
                "ocean_thickness.res.nc.0001": "md5hash1"
            }
      },
}
```
This collate_mapping.log file is currently stored under:
```shell
archive/payu_jobs/10/
|── collate
│    |── 1657xxxx.gadi-pbs.json
│    └── collate_mapping.log
|── run
    └── 1657yyyy.gadi-pbs.json
```
Thanks :)

**Comment by jo-basevi** [comment]
Looks good to me. If we want to include this in telemetry, I think we should include the json in `collate_mapping.log` as a subsection in the collate job file: 1657xxxx.gadi-pbs.json. E.g. the run job files has a section for manifests.

**Comment by Qian-HuiChen** [comment]
Besides the structure of mapping log, it will be very appreciated if you can provide any feedback on this new print out of `payu status` :)
```
========================================
Run: 11
----------------------------------------
  Job ID:            10000000.gadi-pbs
  Run ID:            abcdef
  Stage:             archive
  Total Queue Time:  0h 0m 54s
  Model Finish Time: 1901-01-01T00:00:00
  Exit Status:       0 (Success)
  Model Exit Code:   0 (Success)
  Output Log:        /xxx/access-om2/1deg_jra55_ryf/yy.o100000
  Error Log:         /xxx/access-om2/1deg_jra55_ryf/yy.e10000
  Job File:          /scratch/xxx/access-om2/archive/1deg_jra55_ryf-000/payu_jobs/11/run/10000000.gadi-pbs.json
  ---------- Collate Info ----------
  Job ID:            1111111111.gadi-pbs
  Stage:             exited
  Exit Status:       0 (Success)
  Output Log:        /home/xxx/access-om2/1deg_jra55_ryf/yy_c.o11111111
  Error Log:         /home/xxx/access-om2/1deg_jra55_ryf/yyy_c.e11111111
  Job File:          /scratch/xxx7/access-om2/archive/1deg_jra55_ryf-000/payu_jobs/11/collate/1111111111.gadi-pbs.json
========================================
```

**Comment by aidanheerdegen** [comment]
The information that is stored, and the data structure in which it is stored, is largely dictated by use case.

The use case in the original issue description is still the only one that comes to mind, so I'll concentrate on that in the first instance.

That use case is to be able to reliably reproduce an experiment run even if the original restarts have been collated into a new file and the uncollated restarts have been deleted: which in practice means creating a new `restart.yaml` manifest.

The original restarts are stored in a manifest file which look like
```yaml
work/ocean/INPUT/ocean_velocity.res.nc-0001:
  fullpath: /fullpathtorestart/ocean/ocean_velocity.res.nc.0001
  hashes:
    binhash: 1a8f7447e346a0b92635d633c956bcee
    md5: 287edec7690400b797b1cbf6e1ea60f0
work/ocean/INPUT/ocean_velocity.res.nc-0002:
  fullpath: /fullpathtorestart/ocean/ocean_velocity.res.nc.0002
  hashes:
    binhash: 6d0e1ef20375d2289f4397bab2cdf57b
    md5: 653ffae21c9f0a18718d441d591798a1
work/ocean/INPUT/ocean_velocity.res.nc-0003:
  fullpath: /fullpathtorestart/ocean/ocean_velocity.res.nc.0003
  hashes:
    binhash: 92eb270787b9427a594d58cf85b8f980
    md5: fab54ae81945add9ae5e850a4569ec34
```

and the collated restart would be a single entry
```yaml
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /fullpathtorestart/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4b3832c8775cbbeb9f69762712e1772c
    md5: 2b181afa9524673b64612f3094427fbe
```

To unambiguously associate the uncollated with the collated would require matching all the uncollated `md5` hashes with the collated `md5` hashes, it would also require that no hashes were left unmatched.

What might this look like in practice? I can see a couple of approaches:

1. Lookup backwards: iterate over all the entries in a restart manifest, find every file that is missing (because not all restart files are collated), and use a mapping to find a matching collated restart file. For every match delete the uncollated entry from the manifest and add every collated restart file to the manifest (only once). If there are any uncollated restarts left after this process then error out.

For this approach an ideal data structure would be uncollated:collated md5 hashes in key:value pairs , e.g. in `python`
```python
mapping= {
    '287edec7690400b797b1cbf6e1ea60f0': '2b181afa9524673b64612f3094427fbe', 
    '653ffae21c9f0a18718d441d591798a1': '2b181afa9524673b64612f3094427fbe', 
    'fab54ae81945add9ae5e850a4569ec34' :'2b181afa9524673b64612f3094427fbe', 
    ....}
```
It doesn't have to stored on disk this way as it involves a lot of wasteful duplication. It could be stored as the collated hash key with a tuple/array of uncollated hashes. e.g
```json
{
    "2b181afa9524673b64612f3094427fbe": [
                "287edec7690400b797b1cbf6e1ea60f0",
                "653ffae21c9f0a18718d441d591798a1", 
                "fab54ae81945add9ae5e850a4569ec34"
    ]
}
```
and then generate the mapping above in python.

2. Lookup forwards: for all collated files in the mapping iterate over the restart manifest and find and delete matching uncollated restarts, and add the collated restart once all matching complete. Once it is written out it can be run and tested, which would pick up if there are missing restarts because of missing mappings.

For this approach an ideal data structure would be collated:uncollated md5 hashes in key:array pairs , e.g. in `python`
```python
mapping= {
    "2b181afa9524673b64612f3094427fbe": [
                "287edec7690400b797b1cbf6e1ea60f0",
                "653ffae21c9f0a18718d441d591798a1", 
                "fab54ae81945add9ae5e850a4569ec34"
                ],    
    ....}
```
Which corresponds to the json serialisation above, e.g.
```json
{
    "2b181afa9524673b64612f3094427fbe": [
                "287edec7690400b797b1cbf6e1ea60f0",
                "653ffae21c9f0a18718d441d591798a1", 
                "fab54ae81945add9ae5e850a4569ec34"
    ]
}
```

For simplicity I'd go for option 2.

I don't think we need to store any other information, e.g. paths, for this purpose. If it is machine-readable only the extra information takes up space, is not required, and has the potential to be out of date/inconsistent if paths are amended.
