### ISSUE TITLE
Support for initial conditions files

### ISSUE THREAD

**Issue by anton-seaice** [payu-org/payu#548]
Its been [highlighted](https://forum.access-hive.org.au/t/payu-collation-not-working-in-access-om2-1deg/4068/8) that the current behaviour of copying initial conditions files to every payu work directory, even when they are not longer needed because the model has already run and created restart files, is confusing.

The `restart:` option in config.yaml to start a 'new' experiment from an existing restart directory could provide a better place to put initial conditions files, however it's not perfect:
- We have been specifying input files as individual files, instead of directories (e.g. https://github.com/ACCESS-NRI/access-om2-configs/blob/fce24e35bdf35720a15b6b03fa3616d3486f50b4/config.yaml#L64C1-L67C117)
- What happens if you do a `payu clone --restart` but there are already values in the `restart:` section - do they get overwritten ?

(related: https://github.com/ACCESS-NRI/access-om2-configs/issues/155)

**Comment by jo-basevi** [comment]
I think with the current `restart:` option, it would require a directory structure with directories the same names as sub-models in the `config.yaml`, e.g. `ocean`, `atmosphere`, `ice`. So maybe to specify a individual files for a sub-model, we could add a `restart` option to the sub-model config, e.g.:

```yaml
- name: ocean
  model: mom
  exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-qji4nlmr6utrribaiyhewe4je6mifguz/bin/fms_ACCESS-OM.x
  input:
      - /g/data/vk83/experiments/inputs/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/grid_spec.nc
          # ...
  restart:
     - /g/data/vk83/experiments/inputs/access-om2/ocean/initial_conditions/global.1deg/2020.10.22/ocean_temp_salt.res.nc  
 ````

Though that might be confusing when there's a directory defined under the top-level `restart:` as that probably should take precedence..

> What happens if you do a payu clone --restart but there are already values in the restart: section - do they get overwritten ?

Yes, currently payu overwrites any existing values in the `restart:` section.
