### ISSUE TITLE
Supporting cross platform configurations

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#586]
Scheduler information is platform dependent and it is defined in the `config.yaml`, which means a configuration is platform specific.

ACCESS-NRI needs to support configurations on multiple HPC platforms, which would mean having duplicate [model congfigurations](https://github.com/ACCESS-NRI/access-esm1.5-configs) that differ only in the scheduler information.

If `payu` could support specifying the scheduler information for multiple platforms, the same configuration could seamlessly support multiple HPC platforms/targets.

### Proposal

`payu` support multiple platform/site specific scheduler information, e.g.

```yaml
site:
  gadi:
    project: xx99
    queue: normal
    walltime: 2:30:00
    jobfs: 1500MB
  setonix:
    project: project123
    queue: work
    walltime: 2:00:00
```

and/or if `payu` [supported including yaml files](https://stackoverflow.com/a/9577670)

```yaml
site:
  !include gadi.yaml
  !include setonix.yaml
```
`gadi.yaml`:
```yaml
 gadi:
  project: xx99
  queue: normal
  walltime: 2:30:00
  jobfs: 1500MB
```

`setonix.yaml`:
```yaml
setonix:
  project: project123
  queue: work
  walltime: 2:00:00
```

Note: this syntax could be extended to support multiple queues at a single `site`, but there are likely accompanying configuration changes so not sure it is that useful. It would also require some way of specifying which queue/environment was required from the command line, whereas `site` can be inferred automatically.

Related issues: #182 #323 #568
